#
# dracula theme

description = "theme template"
type = "dark"
version = "1.0.0"

[colors]
# Create a table of source colors and names that match the names set by
# whoever designed the color palette. Grouping them in a source table
# makes it super clear when you are using source colors from the palette.
#
# https://draculatheme.com/contribute#color-palette

source.background_lighter = "#424450"
source.background_light = "#343746"
source.background = "#282a36"
source.background_dark = "#21222C"
source.selection = "#44475a"
source.foreground = "#f8f8f2"
source.comment = "#6272a4"
source.cyan = "#8be9fd"
source.green = "#50fa7b"
source.orange = "#ffb86c"
source.pink = "#ff79c6"
source.purple = "#bd93f9"
source.red = "#ff5555"
source.yellow = "#f1fa8c"


# colors can't be lighter and darker because we need the same descriptors
# to work whether it's a light mode theme or a dark mode theme
# so we use "more" and "less" to indicate more or less contrast
#
# that way
#     {{color.foreground}} on {{color.background_more}}
# will always have more contrast than
#     {{color.foreground}} on {{color.background_less}}
# and
#     {{color.foreground_more}} on {{color.background}}
# will always have more contrast than
#     {{color.foreground_less}} on {{color.background}}
#
#

# foreground colors
#
# for a dark theme more2 should be the closest
# to white, and less2 should be the closest to black
#
# for a light theme more2 should be the closest
# to black, and less2 should be the closest to white
#
# for a one color foreground palette, set them all to
# be the same
#
# for a three color foreground palette set all the 'more'
# values to be the same, and all the 'less' values
# to be the same
#
# for a five color foreground palette set more2 and more
# to be the same, and less2 and less to be the same
foreground_more2 = "{{ colors.foreground }}"
foreground_more1 = "{{ colors.foreground }}"
foreground_more = "{{ colors.foreground }}"
foreground =  "#b2cacd"
foreground_less = "{{ colors.foreground }}"
foreground_less1 = "{{ colors.foreground }}"
foreground_less2 = "{{ colors.foreground }}"

# standard background colors
#
# for a dark theme more3 should be the closest
# to black, and low3 should be the closest to white
#
# for a light theme more3 should be the closest
# to white, and less3 should be the closest to black
#
# for a one color background palette, set them all to
# be the same as background
#
# for a three color background palette set all the 'more'
# values to be the same, and all the 'less' values
# to be the same
#
# for a five color background palette set more2 and more
# to be the same, and less2 and less to be the same
background_more2 = "{{ colors.background }}"
background_more1 = "{{ colors.background }}"
background_more = "{{ colors.background }}"
background =  "#031417"
background_less = "{{ colors.background }}"
background_less1 = "{{ colors.background }}"
background_less2 = "{{ colors.background }}"

##
## named colors
##
# these are the 12 colors in an RGB color wheel
# primary colors: red, yellow, blue
# secondary colors: cyan, magenta, yellow
# tertiary colors: orange, chartreuse_green, spring_green,
#                  azure, violet, rose
#
# there is not universal alignment with the names of these colors
# we use the names from https://en.wikipedia.org/wiki/Color_wheel
# if your palette has a color in the general range of these
# segments of the color wheel, put it in here
#
# these are useful for having directories displayed in green
# no matter what shade of green is in the palette
#
# if your theme only has one blue color, make cyan, azure, and blue all be
# that color. If your theme has three purple colors, pick your best
# one for violet, and put the others as accent colors below. If you have
# leave one blank, go ahead.
#
# we define these both as colors and styles so that if you need to define
# style that's bold red you can do "bold {{color.red}}"
red = "{{ colors.red }}"
orange = "{{ colors.orange }}"
yellow = "{{ colors.yellow }}"
chartreuse_green = ""
green = "{{ colors.green }}"
spring_green = ""
cyan = "{{ colors.cyan }}"
azure = ""
blue = ""
violet = "{{ colors.purple }}"
magenta = "{{ colors.pink }}"
rose = ""

##
## ansi colors
##
## optional map/create colors for the 16 ansi colors
ansi.black = "#21222c"
ansi.red = "#ff5555"
ansi.green = "#50fa7b"
ansi.yellow = "#f1fa8c"
ansi.blue = "#bd93f9"
ansi.magenta = "#ff79c6"
ansi.cyan = "#8be9fd"
ansi.white = "#f8f8f2"
ansi.bright_black = "#6272a4"
ansi.bright_red = "#ff6e6e"
ansi.bright_green = "#69ff94"
ansi.bright_yellow = "ffffa5"
ansi.bright_blue = "#d6acff"
ansi.bright_magenta = "#ff92df"
ansi.bright_cyan = "#a4ffff"
ansi.bright_white = "#ffffff"

##
## accent colors
##
# say you only have 5 accent colors, make 5-12 all be the same
#
accent.1= "violet"
accent.2 = ""
accent.3 = ""
accent.4 = ""
accent.5 = ""
accent.6 = ""
accent.7 = ""
accent.8 = ""
accent.9 = ""
accent.10 = ""
accent.11 = ""
accent.12 = ""

# sometimes you need a set of 3 or a set of 4 accents that look good together
# define those here. your triads don't have to be evenly across from each other
# on the color wheel, it's just fine to have a dark purple, a light purple, and
# a gold, or whatever. Same thing for the tetrad
triad.1 = ""
triad.2 = ""
triad.3 = ""

tetrad.1 = "purple"
tetrad.2 = "orange"
tetrad.3 = "cyan"
tetrad.4 = "green"


[styles]
# text is the normal foreground and background colors
text = "{{colors.foreground}} on {{colors.background}}"
# text_dim is just like text, but with less contrast to the background
# by changing the foreground color
text_dim = "{{colors.foreground_less}} on {{colors.background}}"
selected = "{{colors.foreground}} on {{colors.background_less}}"


# think of it the same as the current line in many coding
# themes. You probably want to use this in fzf
highlighted_line = "{{ colors.foreground }} on {{ colors.background_medium }}"

# sometimes you have things selected that aren't currently highlighted
# like a "choose several" type of selection box
selected_line = "{{ colors.foreground}} on {{ colors.source.current_line}}"

##
## warnings and errors
##
# create styles for errors, warnings, and notices
text_error = "{{ color.red }}"
text_warning = "{{ color.yellow }}"
text_notice = "{{ color.source.comment }}"

##
## accent colors
##
# list 12 accent colors. your reddest should be 1, moving clockwise around
# the rbg color wheel. If you have fewer than 12 accents, TODO???
#
# CAUTION: if you use subtable elements that are numeric, you have to
# reference them like {{ color['accent.1'] }} instead of {{ color.accent.2 }}.
# jinja thinks a bare number should be an integer type, and toml always interprets
# key values as strings
#
accent.1= "{{ color['accent.1'] }}"
accent.2 = "{{ color['accent.2'] }}"
accent.3 = "{{ color['accent.3'] }}"
accent.4 = "{{ color['accent.4'] }}"
accent.5 = "{{ color['accent.5'] }}"
accent.6 = "{{ color['accent.6'] }}"
accent.7 = "{{ color['accent.7'] }}"
accent.8 = "{{ color['accent.8'] }}"
accent.9 = "{{ color['accent.9'] }}"
accent.10 = "{{ color['accent.10'] }}"
accent.11 = "{{ color['accent.11'] }}"
accent.12 = "{{ color['accent.12'] }}"

# sometimes you need a set of 3 or a set of 4 accents that look good together
# define those here. your triads don't have to be evenly across from each other
# on the color wheel, it's just fine to have a dark purple, a light purple, and
# a gold, or whatever. Same thing for the tetrad
triad.1 = "{{ color['triad.1'] }}"
triad.2 = "{{ color['triad.2'] }}"
triad.3 = "{{ color['triad.3'] }}"

tetrad.1 = "{{ color['tetrad.1'] }}"
tetrad.2 = "{{ color['tetrad.2'] }}"
tetrad.3 = "{{ color['tetrad.3'] }}"
tetrad.4 = "{{ color['tetrad.4'] }}"

##
## ui elements
##
# use these generic ui element definitions in your pattern to use the same colors
# for various parts of the 'UI' in different tools (i.e. fzf vs less)
#
ui.title = ""
ui.label = ""
ui.border = ""
ui.prompt = ""
ui.pointer = ""
ui.marker = ""
ui.scrollbar = ""
ui.query = ""
ui.column_header = ""
